// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRzgeyL7kbiot7XgRH7Ly0VCcSiNhoWtk',
    appId: '1:648521779279:android:1840ab0f52ea2f2786c23a',
    messagingSenderId: '648521779279',
    projectId: 'mobile-payment-fyp',
    databaseURL: 'https://mobile-payment-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-payment-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAk0E6Kx4UiAMXiCPPcsehmD0R885AbNw',
    appId: '1:648521779279:ios:0a8cbfd78d3707fa86c23a',
    messagingSenderId: '648521779279',
    projectId: 'mobile-payment-fyp',
    databaseURL: 'https://mobile-payment-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-payment-fyp.appspot.com',
    iosClientId: '648521779279-9md1ogq0j4n7933fca476v46gnrs1gp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );
}
